# Pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-illegal-windows-names
      - id: check-builtin-literals
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: name-tests-test
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
        args: ["--all", "--in-place"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes", "--exit-zero"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write"]
        files: \.(json|md|yaml|yml|html|css|qml)$
        additional_dependencies:
          - "prettier@3.6.2"
          - "@prettier/plugin-xml"

  # - repo: https://github.com/baiyao105/qml-formatter
  #   rev: v1.0.1
  #   hooks:
  #     - id: qml-format

  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7
  #   hooks:
  #     - id: actionlint
